### ISSUE TITLE
No output generated - read_mosaic-related? 

### ISSUE THREAD

**Issue by lassedochreden** [jhausserlab/HiFiAlignmentTool#14]
Hi, 

thanks for providing this nice tool. 

Unfortunately, I am running into problems with the initial reassembling step (under Python **3.9.18** and Windows in an HPC environment; more info below). 

The tool correctly detects the czi images, generates following output: 

```
 Found the following image files in ./czi:

2024_07_03__B14_30715_4_3_CK5488_CK7555_CK19647.czi
2024_07_04__B14_30715_4_3_Wnt4488_Sox9555_CD24647.czi

--- Processing: ./czi/2024_07_03__B14_30715_4_3_CK5488_CK7555_CK19647.czi
info – czi dim_shape:  [{'X': (0, 2040), 'Y': (0, 2040), 'C': (0, 4), 'M': (0, 1108), 'S': (0, 1)}]
info – czi channels:  4 
```

BUT then stops and does not generated any further output. 

Looking a bit into the source code, this seems related to **czi.py** and the **get_reassembled_czi(czi)** function, more specifically **czi.read_mosaic(C=channel, scale_factor=1)** (which also has some error-related comments). 

Is this is a known problem and is there a fix for it? 

Thanks in advance for any help (I am not a Python expert) - Happy to provide further information!

**Comment by jhausser** [comment]
Hi Lasse, thanks for letting us know about this issue! I'm sorry to say that I can't help because the people who wrote this package (Axel de Tonnac mainly, with contributions from Fabian Schilling, and Fredrik Carlsson) have left my lab and moved to new positions. I don't have experience running this package myself, having only written a very early version in ImageJ. I hope you can understand that it's a challenge inherent to maintaining software developed in an academic setting. Yours, Jean
